# Generated by Django 3.2.3 on 2021-05-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bolog',
            new_name='Blog',
        ),
    ]
